#!/bin/bash

pwd
hostname
date

dataset_arg=$1
target_arg=$2
echo ${dataset_arg}
echo ${target_arg}

# Load conda and active UnitedMet environment
conda_path="~/.bashrc"
cd /data1/reznike/wangs13/UnitedMet

job1="init"
job2="pyro"
job3="posterior"
job4="summary"
script1="Performance_Benchmarking.scripts.CV_initialization"
script2="Performance_Benchmarking.scripts.CV_pyro"
script3="Performance_Benchmarking.scripts.CV_posterior"
script4="Performance_Benchmarking.scripts.CV_summarization"

cv_opts="--crossval_dims 1 202 --crossval_steps 10 --crossval_folds 10"
svi_opts="--n_steps 2000 --learning_rate 0.001"
# calculate number of jobs in the job array, n_indices = n_folds * len(n_dims_options)
#10*11=110 for 102, 10*21=210 for 202
n_indices=210


file_path="/data1/reznike/wangs13/UnitedMet/"
rna_matched_data_dir="/data1/reznike/wangs13/UnitedMet/data/RNA_matched_PanCancer"
met_matched_data_dir="/data1/reznike/wangs13/UnitedMet/data/MET_matched_PanCancer"
#rna_imputation_data_dir="/data1/reznike/xiea1/MetabolicModel/data/RNA_matched_imputation"
results_dir="/data1/reznike/wangs13/UnitedMet/results_RNA_PanCancer_${dataset_arg}_CV"

# submit trial jobs
logs_dir="${results_dir}/logs"
echo $(pwd)
echo ${results_dir}
echo ${logs_dir}
mkdir -p ${results_dir} ${logs_dir}
# The first job of CV_initialization only needs to be run once. It will empty existing cv scores files.
jid1=$(sbatch --parsable -p componc_cpu -J "${job1}" -N 1 -n 1 -c 10 --mem=10G -t 0:15:00 -o ${logs_dir}/${job1}_%j.stdout -e ${logs_dir}/${job1}_%j.stderr --wrap="source ${conda_path};conda activate UnitedMet;python3 -m ${script1} ${cv_opts} -fp ${file_path} -ct PanCancer -t ${target_arg} -rd ${results_dir}")
jid2=$(sbatch --parsable -p componc_cpu -J "${job2}" --array=1-${n_indices} --depend=afterok:$jid1 -N 1 -n 1 -c 20 --mem=20G -t 1:59:00 -o ${logs_dir}/${job2}_%j.stdout -e ${logs_dir}/${job2}_%j.stderr --wrap="source ${conda_path};conda activate UnitedMet;python3 -m ${script2} -rd ${results_dir} ${cv_opts} ${svi_opts}")
jid3=$(sbatch --parsable -p componc_cpu -J "${job3}" --array=1-${n_indices} --depend=afterok:$jid2 -N 1 -n 1 -c 24 --mem=96G -t 0:30:00 -o ${logs_dir}/${job3}_%j.stdout -e ${logs_dir}/${job3}_%j.stderr --wrap="source ${conda_path};conda activate UnitedMet;python3 -m ${script3} -rd ${results_dir} ${cv_opts}")
sbatch -p componc_cpu -J "${job4}" --depend=afterok:$jid3 -N 1 -n 1 -c 10 --mem=10G -t 0:15:00 -o ${logs_dir}/${job4}_%j.stdout -e ${logs_dir}/${job4}_%j.stderr --wrap="source ${conda_path};conda activate UnitedMet;python3 -m ${script4} -rd ${results_dir} ${cv_opts}"



echo "cv options:"
echo $cv_opts
echo "Starting job..."
echo "The path is $PATH"
echo "start time $(date)"